### ISSUE TITLE
Travis knows not about dot

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#131]
We have a build failure because there Travis doesn't have graphviz

ERROR: test_meta (tests.test_scripts.test_gen_graphviz.GraphvizTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/graphviz/backend.py", line 111, in run
    proc = subprocess.Popen(cmd, **kwargs)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

**Comment by cmungall** [comment]
While it should be possible to tweak the travis (either do a separate install or use Docker), I am inclined to simply skip this test as part of the travis build for now

**Comment by hsolbrig** [comment]
Makes sense.  Will do

---- Chris Mungall wrote ----
