### ISSUE TITLE
Error instantiating relationship type

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#178]
trying experiments with python bindings:

```
>>> bl.Association(id='x',subject='x',relation=None,object='x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 20, in __init__
  File "/Users/cjm/repos/biolink-model/metamodel/utils/yamlutils.py", line 11, in __post_init__
    self._fix_elements()
  File "/Users/cjm/repos/biolink-model/biolinkmodel/datamodel.py", line 1702, in _fix_elements
    raise ValueError(f"relation must be supplied")
ValueError: relation must be supplied
```

can be traced to:
```
>>> r = bl.RelationshipType('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
```

traced to:

```
@dataclass
class RelationshipType(YAMLRoot):
    """
    An OWL property used as an edge label
    """
    pass
```

**Comment by hsolbrig** [comment]
Not sure I understand the issue.  While the error message could be clearer, `relation` is a required slot, so `relation=None` is not valid.

**Comment by cmungall** [comment]
ah sorry, this is what I was actually trying to do:

```
>>> import biolinkmodel.datamodel as bl
>>> bl.Association(id='foo:1',subject='s',relation='r',object='o')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 20, in __init__
  File "/Users/cjm/repos/biolink-model/metamodel/utils/yamlutils.py", line 11, in __post_init__
    self._fix_elements()
  File "/Users/cjm/repos/biolink-model/biolinkmodel/datamodel.py", line 1704, in _fix_elements
    self.relation = RelationshipType(self.relation)
TypeError: __init__() takes 1 positional argument but 2 were given
```

digging deeper it seemed the issue was in creating the Relation field itself

I see now I can do this:

```
>>> bl.Association(id='foo:1',subject='s',relation=bl.RelationshipType(),object='o')
Association(id='foo:1', name=None, category=[], related_to=None, node_property=None, iri=None, full_name=None, description=None, systematic_synonym=None, association_type=None, subject='s', negated=False, relation=RelationshipType(), object='o', qualifiers=[], publications=[], provided_by=None, association_slot=None)
```

but this is not my intent as I want to be able to specify a named relation here. However, the fault is entirely in my specification of the yaml rather than the framework
