### ISSUE TITLE
Error when trying to build the model

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#345]
Running into the following error when trying to build the model from YAML:
```sh
ValueError: File: /Users/deepak.unni3/GIT/biolink-model-fork/biolink-model.yaml Slot: has input domain (occurrent) does not match declaring class "(biological process or activity)"
```

Full traceback:
```sh
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gen-yuml", line 10, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/biolinkml/generators/yumlgen.py", line 236, in cli
    print(YumlGenerator(yamlfile, format).serialize(classes=classes, directory=directory), end="")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/biolinkml/generators/yumlgen.py", line 42, in __init__
    super().__init__(schema, fmt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/biolinkml/utils/generator.py", line 52, in __init__
    loader.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/biolinkml/utils/schemaloader.py", line 109, in resolve
    self.raise_value_error(f'Slot: {slot.name} domain ({slot.domain}) '
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/biolinkml/utils/schemaloader.py", line 433, in raise_value_error
    raise ValueError(f'File: {self.schema.source_file} {error}')
ValueError: File: /Users/deepak.unni3/GIT/biolink-model-fork/biolink-model.yaml Slot: has input domain (occurrent) does not match declaring class "(biological process or activity)"
```

But the definition of `has input` slot seems correct. 

@cmungall @hsolbrig Thoughts?

**Comment by deepakunni3** [comment]
Fixed via 380df19
