### ISSUE TITLE
Not using latest biolinkml in build

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#410]
If you look at biolink/model.py you will note that it was generated from biolinkml v 1.4.x  -- you should be building from 1.5.3 (although we will be adding a new version shortly).  Is this a requirements issue?

**Comment by cmungall** [comment]
We definitely want to be using 1.5.4 (need to wait due to owlgen bug in
1.5.3)

**Comment by deepakunni3** [comment]
Tried to build biolink model with 1.5.4 but got the following stack trace when generating `biolink-model.ttl`,
```
WARNING:rdflib.term:https://w3id.org/biolink/vocab/has variant part does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/homologous to does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/molecularly interacts with does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/molecularly interacts with does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/derives into does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/derives from does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/has phenotype does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/related condition does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/related condition does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/model of does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/expressed in does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/has gene product does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/part of does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:https://w3id.org/biolink/vocab/develops from does not look like a valid URI, trying to serialize this will break.
Traceback (most recent call last):
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/bin/gen-rdf", line 8, in <module>
    sys.exit(cli())
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/biolinkml/generators/rdfgen.py", line 52, in cli
    print(RDFGenerator(yamlfile, **kwargs).serialize(**kwargs))
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/biolinkml/utils/generator.py", line 112, in serialize
    self.end_schema(**kwargs)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/biolinkml/generators/rdfgen.py", line 42, in end_schema
    print(self._data(graph))
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/biolinkml/generators/rdfgen.py", line 30, in _data
    return g.serialize(format='turtle' if self.format == 'ttl' else self.format).decode()
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/graph.py", line 964, in serialize
    serializer.serialize(stream, base=base, encoding=encoding, **args)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/plugins/serializers/turtle.py", line 247, in serialize
    if self.statement(subject) and not firstTime:
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/plugins/serializers/turtle.py", line 314, in statement
    return self.s_squared(subject) or self.s_default(subject)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/plugins/serializers/turtle.py", line 319, in s_default
    self.predicateList(subject)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/plugins/serializers/turtle.py", line 422, in predicateList
    self.objectList(properties[predicate])
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/plugins/serializers/turtle.py", line 433, in objectList
    self.path(objects[0], OBJECT)
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/plugins/serializers/turtle.py", line 333, in path
    or self.p_default(node, position, newline)):
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/plugins/serializers/turtle.py", line 339, in p_default
    self.write(self.label(node, position))
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/plugins/serializers/turtle.py", line 355, in label
    return self.getQName(node, position == VERB) or node.n3()
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/rdflib/term.py", line 254, in n3
    raise Exception('"%s" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?'%self)
Exception: "https://w3id.org/biolink/vocab/develops from" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?
make: *** [biolink-model.ttl] Error 1

```

It looks like predicates of the form `has phenotype`, `develops from`, `has gene product` are not converted from sentence case to snake_case.
This was working in biolinkml 1.5.1. Unclear what changed since then.

**Comment by cmungall** [comment]
it's possible related to changes I made a while ago... I changed uri
generation to be in the correct namespace but may have not used the case
normalization, the current tests don't have spaces in slot names

**Comment by hsolbrig** [comment]
This appears to be an issue with the rdf generator in particular -- for some reason the temporary JSON-LD is building one of the contexts wrong.

**Comment by cmungall** [comment]
I don't think we use the json-ld contexts in owlgen though

**Comment by hsolbrig** [comment]
Perhaps a different bug report?   The issue above was for gen-rdf.  Is it not generating OWL as well?

**Comment by deepakunni3** [comment]
@cmungall The OWL generation is fixed in `1.5.4`
@hsolbrig Thanks for the PR. I did not realize that it was look at the wrong JSON-LD context for generation of the TTL.

**Comment by hsolbrig** [comment]
NP - fwiw it seems to have been working for a long time.  One thing to note on this, however, is that the way it works right now, you may need to do two commits -- generate the context.jsonld, push so that it shows up in the w3id reference and then generate the ttl.   I *think* you should be able to build the context.jsonld in the make file as a dependency and then reference it directory (--context <path>/context.jsonld)

**Comment by cmungall** [comment]
Apologies for the confusion re ttl/owl

We should probably have better conventions for names here, as we often want to distribute the products of gen-owl as .ttl files. Something like foo-ontol.SUFFIX for the OWL product.

**Comment by hsolbrig** [comment]
Yup - the old syntax/semantics issue.  We've got the same problem with `.context.jsonld` vs. `.jsonld` vs. `.json`.  To really confuse things, while it may be less than ideal, there is nothing preventing you from emitting owl as `.jsonld` either...

**Comment by cmungall** [comment]
So what is the fix here?

**Comment by deepakunni3** [comment]
Whoops.. this is fixed since our build is working on biolinkml 1.5.4

**Comment by hsolbrig** [comment]
"@deepakunni3  Thanks for the PR. I did not realize that it was look at the wrong JSON-LD context for generation of the TTL. "  -- I turns out I lied.  It was the right and there is an issue in parsing `subproperty_of` -- see https://github.com/biolink/biolink-model/issues/421
